name: auto-excel-publication
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - configparser=5.0.2
  - et_xmlfile=1.1.0
  - intel-openmp=2021.4.0
  - libffi=3.4.2
  - libprotobuf=3.20.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numexpr=2.8.3
  - numpy=1.23.1
  - numpy-base=1.23.1
  - openpyxl=3.0.10
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.3
  - pip=22.1.2
  - protobuf=3.20.1
  - pyparsing=3.0.9
  - python=3.10.4
  - python-dateutil=2.8.2
  - pytz=2022.1
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.2
  - tk=8.6.12
  - toml=0.10.2
  - tzdata=2022c
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.12
