tag_list = [
    "<Coverage,Open active practices>",
    "<Coverage,Count of practices included>",
    "<Coverage,Practice coverage>",
    "<Coverage,Registered patients at open active practices>",
    "<Coverage,Registered patients at included practices>",
    "<Coverage,Patient coverage>",
    "<Coverage,>",
    "<Working Days,Number of working weekdays>",
    "<Coverage,>",
    "<Appointment Count,Total count of appointments1>",
    "<Appointment Count,Estimated England total count of appointments2>",
    "<Appointment Count,_>",
    "<Appointment Count,Covid Vaccination appointments removed from GP Appointments Data return 8>",
    "<Appointment Count,>",
    "<Appointment Count,Covid Vaccination delivered by practice/PCN 9>",
    "<Appointment Count,Estimated England total count of appointment including covid vaccinations 9,10>",
    "<Appointment Status,Attended>",
    "<Appointment Status,Did Not Attend>",
    "<Appointment Status,Unknown Status>",
    "<Appointment Status,>",
    "<SDS Role Group,GP>",
    "<SDS Role Group,Nurses>",
    "<SDS Role Group,Other Direct Patient Care>",
    "<SDS Role Group,Data Quality>",
    "<SDS Role Group,Unknown SDS Role Group>",
    "<SDS Role Group,>",
    "<Appointment Mode,Face-to-Face>",
    "<Appointment Mode,Home Visit>",
    "<Appointment Mode,Telephone>",
    "<Appointment Mode,Video/Online>",
    "<Appointment Mode,Unknown Mode6>",
    "<Time between,Same Day>",
    "<Time between,1 Day>",
    "<Time between,2 to 7 Days>",
    "<Time between,8  to 14 Days>",
    "<Time between,15  to 21 Days>",
    "<Time between,22  to 28 Days>",
    "<Time between,More than 28 Days>",
    "<Time between,Unknown / Data Quality>",
    "<Service Setting,General Practice>",
    "<Service Setting,Primary Care Network>",
    "<Service Setting,Extended Access Provision>",
    "<Service Setting,Other>",
    "<Service Setting,Unmapped Service Setting>",
    "<Service Setting,>",
    "<Context Type,Care Related Encounter>",
    "<Context Type,General Consultation Acute>",
    "<Context Type,General Consultation Routine>",
    "<Context Type,Planned Clinics>",
    "<Context Type,Planned Clinical Procedure>",
    "<Context Type,Unplanned Clinical Activity>",
    "<Context Type,Walk-in>",
    "<Context Type,Clinical Triage>",
    "<Context Type,Home Visit>",
    "<Context Type,Care Home Visit>",
    "<Context Type,Group Consultation and Group Education>",
    "<Context Type,Structured Medication Review>",
    "<Context Type,Patient contact during Care Home Round>",
    "<Context Type,Care Home Needs Assessment & Personalised Care and Support Planning>",
    "<Context Type,Social Prescribing Service>",
    "<Context Type,Service provided by organisation external to the practice>",
    "<Context Type,Non-contractual chargeable work>",
    "<Context Type,Inconsistent Mapping>",
    "<Context Type,National Category Unmapped>",
    "<Healthcare Proffesional,GP>",
    "<Healthcare Proffesional,Other Practice staff>",
    "<Healthcare Proffesional,Unknown HCP>",
    "<Healthcare Proffesional,>",
    "<Appointment Status,Attended,percent>",
    "<Appointment Status,Did Not Attend,percent>",
    "<Appointment Status,Unknown Status,percent>",
    "<SDS Role Group,GP,percent>",
    "<SDS Role Group,Nurses,percent>",
    "<SDS Role Group,Other Direct Patient Care,percent>",
    "<SDS Role Group,Data Quality,percent>",
    "<SDS Role Group,Unknown SDS Role Group,percent>",
    "<Appointment Mode,Face-to-Face,percent>",
    "<Appointment Mode,Home Visit,percent>",
    "<Appointment Mode,Telephone,percent>",
    "<Appointment Mode,Video/Online,percent>",
    "<Appointment Mode,Unknown Mode6,percent>",
    "<Time Between,Same Day,percent>",
    "<Time Between,1 Day,percent>",
    "<Time Between,2 to 7 Days,percent>",
    "<Time Between,8  to 14 Days,percent>",
    "<Time Between,15  to 21 Days,percent>",
    "<Time Between,22  to 28 Days,percent>",
    "<Time Between,More than 28 Days,percent>",
    "<Time Between,Unknown / Data Quality,percent>",
    "<Service Setting,General Practice,percent>",
    "<Service Setting,Primary Care Network,percent>",
    "<Service Setting,Extended Access Provision,percent>",
    "<Service Setting,Other,percent>",
    "<Service Setting,Unmapped Service Setting,percent>",
    "<Context Type,Care Related Encounter,percent>",
    "<Context Type,General Consultation Acute,percent>",
    "<Context Type,General Consultation Routine,percent>",
    "<Context Type,Planned Clinics,percent>",
    "<Context Type,Planned Clinical Procedure,percent>",
    "<Context Type,Unplanned Clinical Activity,percent>",
    "<Context Type,Walk-in,percent>",
    "<Context Type,Clinical Triage,percent>",
    "<Context Type,Home Visit,percent>",
    "<Context Type,Care Home Visit,percent>",
    "<Context Type,Group Consultation and Group Education,percent>",
    "<Context Type,Structured Medication Review,percent>",
    "<Context Type,Patient contact during Care Home Round,percent>",
    "<Context Type,Care Home Needs Assessment & Personalised Care and Support Planning,percent>",
    "<Context Type,Social Prescribing Service,percent>",
    "<Context Type,Service provided by organisation external to the practice,percent>",
    "<Context Type,Non-contractual chargeable work,percent>",
    "<Context Type,Inconsistent Mapping,percent>",
    "<Context Type,National Category Unmapped,percent>",
    "<Context Type,GP,percent>",
    "<Context Type,Other Practice staff,percent>",
    "<Context Type,Unknown HCP,percent>",
]
